using System;
using Dalamud.Plugin.Services;
using FFXIVClientStructs.FFXIV.Client.UI.Agent;
using LootGoblin.Models;

namespace LootGoblin.Services;

/// <summary>
/// Reads the current map flag marker from AgentMap after a treasure map is deciphered.
/// The game places a flag marker at the treasure location when the map is opened.
/// Converts map coordinates to world coordinates using the Lumina Map sheet.
/// </summary>
public class MapFlagReader : IDisposable
{
    private readonly Plugin _plugin;
    private readonly IPluginLog _log;

    public MapFlagReader(Plugin plugin, IPluginLog log)
    {
        _plugin = plugin;
        _log = log;
    }

    public void Dispose() { }

    /// <summary>
    /// Attempt to read the current map flag from AgentMap.
    /// Returns null if no flag is set or if reading fails.
    /// The flag is set automatically when a treasure map is deciphered.
    /// </summary>
    public unsafe MapLocation? TryReadFlag()
    {
        try
        {
            var agentMap = AgentMap.Instance();
            if (agentMap == null)
            {
                _plugin.AddDebugLog("AgentMap is null.");
                return null;
            }

            // FlagMarkerCount > 0 means a flag has been placed (e.g. after deciphering a treasure map)
            if (agentMap->FlagMarkerCount == 0)
            {
                return null;
            }

            // FlagMapMarkers is the public FixedSizeArray accessor generated by InteropGenerator
            var marker = agentMap->FlagMapMarkers[0];
            var territoryId = marker.TerritoryId;

            if (territoryId == 0)
            {
                _plugin.AddDebugLog("Flag marker has TerritoryId=0, not yet valid.");
                return null;
            }

            // XFloat = world X, YFloat = world Z (FFXIV map Y axis = world Z axis)
            var worldX = marker.XFloat;
            var worldZ = marker.YFloat;

            // World Y (height): use current player height as best guess; nav will handle actual Z
            var localPlayer = Plugin.ObjectTable.LocalPlayer;
            var worldY = localPlayer?.Position.Y ?? 0f;

            // Get zone name from TerritoryType sheet
            var territorySheet = Plugin.DataManager.GetExcelSheet<Lumina.Excel.Sheets.TerritoryType>();
            var territory = territorySheet?.GetRow(territoryId);
            var zoneName = territory?.PlaceName.ValueNullable?.Name.ToString() ?? $"Zone {territoryId}";

            _plugin.AddDebugLog($"Flag: {zoneName} (Territory {territoryId}) → World ({worldX:F1}, {worldY:F1}, {worldZ:F1})");

            return new MapLocation
            {
                TerritoryId = territoryId,
                ZoneName = zoneName,
                X = worldX,
                Y = worldY,
                Z = worldZ,
                IsResolved = true,
            };
        }
        catch (Exception ex)
        {
            _log.Error($"MapFlagReader.TryReadFlag failed: {ex.Message}");
            return null;
        }
    }
}
